### ISSUE TITLE
Support for parsing inlined frames.

### ISSUE THREAD

**Issue by tamaskenez** [getsentry/rust-proguard#5]
Hi, I'm from the Google R8 team. Thanks for adding support for line number optimization!
I'd like to draw your attention to another, related feature used both in Proguard and R8 generated mapping files: inlined frames.

The stack trace for an inlined call contains only the innermost callee without the callers. In the mapping file the stack frame is encoded with multiple line all referring to the same alias position. Example:

    7:8:void method3(long):78:79 -> main
    7:8:void method2(int):87 -> main
    7:8:void method1(java.lang.String):95 -> main
    7:8:void main(java.lang.String[]):101 -> main

The innermost callee, `method3` is a regular line while the subsequent lines describe the callers with only single original source line locations.

Let me know if you have questions.

**Comment by bruno-garcia** [comment]
@tamaskenez thanks a lot for bringing this to us and the clear description.

This surely should be added to this crate. Maybe a PR lands magically here to help us :) Regardless, surely we should eventually prioritize this and add support.
